let pet = 'dog';
console.log("Is pet == 'dog'? I predict True.");
console.log(pet == 'dog');
let yourName = 'Faraz';
console.log("Is yourName == 'Faraz'? I predict True.");
console.log(yourName == 'Faraz');
let place = 'dubai';
console.log("Is palce == 'dubai'? I predict True.");
console.log(place == 'dubai');
let season = 'summer';
console.log("Is season == 'summer'? I predict True.");
console.log(season == 'summer');
let grade = 'A';
console.log("Is grade == 'A'? I predict True.");
console.log(grade == 'A');
let pet1 = 'cat';
console.log("Is pet1 == 'dog'? I predict False.");
console.log(pet1 == 'dog');
let yourName1 = 'Syed';
console.log("Is yourName1 == 'Faraz'? I predict False.");
console.log(yourName1 == 'Faraz');
let place1 = 'Germany';
console.log("Is palce1 == 'dubai'? I predict False.");
console.log(place1 == 'dubai');
let season1 = 'autumn';
console.log("Is season1 == 'summer'? I predict False.");
console.log(season1 == 'summer');
let grade1 = 'B';
console.log("Is grade1 == 'A'? I predict False.");
console.log(grade1 == 'A');
//# sourceMappingURL=assign23.js.map